# Generated by Django 2.2.1 on 2019-06-01 22:08

from django.conf import settings
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumnos',
            fields=[
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('presento', models.BooleanField()),
                ('rut', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('codigoVerificador', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'Alumnos',
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
                ('semestre', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('seccion', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Cursos',
                'unique_together': {('codigo', 'semestre', 'año', 'seccion')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField()),
                ('fechaTermino', models.DateField()),
                ('estado', models.CharField(max_length=50)),
                ('duracion', models.DurationField()),
            ],
            options={
                'db_table': 'Evaluacion',
            },
        ),
        migrations.CreateModel(
            name='Rubrica',
            fields=[
                ('nombre', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=50)),
                ('tiempo', models.DurationField()),
                ('tiempoMin', models.DurationField(default=0)),
                ('archivo', models.FilePathField(default='./', path='./EvPresentaciones/ArchivosRubricas')),
            ],
            options={
                'db_table': 'Rubrica',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Alumnos_Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField(null=True)),
                ('tiempo', models.DurationField(default=0)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EvPresentaciones.Alumnos')),
                ('evaluacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EvPresentaciones.Evaluacion')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EvPresentaciones.Evaluacion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'evaluacion')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion_Rubrica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evaluacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EvPresentaciones.Evaluacion')),
                ('rubrica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EvPresentaciones.Rubrica')),
            ],
            options={
                'unique_together': {('evaluacion', 'rubrica')},
            },
        ),
        migrations.CreateModel(
            name='Cursos_Evaluacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EvPresentaciones.Cursos')),
                ('evaluacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EvPresentaciones.Evaluacion')),
            ],
            options={
                'unique_together': {('curso', 'evaluacion')},
            },
        ),
        migrations.CreateModel(
            name='Cursos_Alumnos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreGrupo', models.CharField(default='No Group', max_length=50, null=True)),
                ('evaluado', models.BooleanField()),
                ('alumnos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EvPresentaciones.Alumnos')),
                ('curso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='EvPresentaciones.Cursos')),
            ],
            options={
                'unique_together': {('curso', 'alumnos')},
            },
        ),
    ]
